package ca.mcgill.ecse321.petshelter;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import java.util.List;
import java.util.Set;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import ca.mcgill.ecse321.petshelter.dao.*;
import ca.mcgill.ecse321.petshelter.model.*;

@ExtendWith(SpringExtension.class)
@SpringBootTest
public class PetShelterPersistenceTests {

	@Autowired
	AdoptRequestRepository adoptRequestRepository;
	
	@Autowired
	AppAdminRepository appAdminRepository;
	
	@Autowired
	AppUserRepository appUserRepository;
	
	@Autowired
	DonationRepository donationRepository;
	
	@Autowired
	PersonRepository personRepository;
	
	@Autowired
	PetPostRepository petPostRepository;
	
	@Autowired
	QuestionRepository questionRepository;
	
	@Autowired
	UserProfileRepository userProfileRepository;
	
	
	
	
	
	@AfterEach
	public void clearDatabase() {
		adoptRequestRepository.deleteAll();
		appAdminRepository.deleteAll();
		appUserRepository.deleteAll();
		donationRepository.deleteAll();
		personRepository.deleteAll();
		petPostRepository.deleteAll();
		questionRepository.deleteAll();
		userProfileRepository.deleteAll();
	}
	
	
	
	

	//AdoptRequest test

	@Test
	public void PersistAndLoadAdoptRequest() {
		Status status = Status.PENDING;
		AdoptRequest adoptRequest = new AdoptRequest();
		adoptRequest.setStatus(status);
		
		
		
		Person person = new Person();
		person.setUsername("hello");
		person.setPassword("world");
		personRepository.save(person);
		adoptRequest.setRequestedBy(person);
		
		
		Person person_dos = new Person();
		person_dos.setUsername("Juan");
		person_dos.setPassword("Pablo");
		personRepository.save(person_dos);
		
		PetPost petPost = new PetPost();
		petPost.setAvailability(true);
		petPost.setDescription("wololo");
		petPost.setName("boohoo");
		petPost.setOwnedBy(person_dos);
		petPost.setTypeOfPet("cat");
		petPostRepository.save(petPost);
		
		adoptRequest.setRequesting(petPost);
		
		
		adoptRequestRepository.save(adoptRequest);
		//id autogenerated on save
		int id = adoptRequest.getAdoptRequestId();
		
		adoptRequest = null;
		
		adoptRequest = adoptRequestRepository.findByAdoptRequestId(id);
		assertNotNull(adoptRequest);
		assertEquals(status, adoptRequest.getStatus());

		
		
	}
	
	
	//AppAdmin test
	@Test
	public void PersistAndLoadAppAdmin() {
		String username = "Michael";
		String password = "Admin";
		AppAdmin appAdmin = new AppAdmin();
		appAdmin.setPassword(password);
		appAdmin.setUsername(username);
		
		appAdminRepository.save(appAdmin);
		
		appAdmin = null;
		appAdmin = appAdminRepository.findByUsername(username);
		assertNotNull(appAdmin);
		assertEquals(username, appAdmin.getUsername());
		assertEquals(password, appAdmin.getPassword());
	}
	
	
	//AppUser test
	@Test
	public void PersistAndLoadAppUser() {
		String username = "JWS";
		String password = "3GPA";
		PersonRole personRole = PersonRole.ADOPTER;
		
		AppUser appUser = new AppUser();
		appUser.setPassword(password);
		appUser.setUsername(username);
		appUser.setAppUserRole(personRole);
		appUserRepository.save(appUser);
		
		appUser = null;
		
		appUser = appUserRepository.findByUsername(username);
		assertNotNull(appUser);
		assertEquals(username, appUser.getUsername());
		assertEquals(password, appUser.getPassword());
		assertEquals(personRole, appUser.getAppUserRole());
		
	
	}
	
	
	
	@Test
	public void testPersistAndLoadPerson() {
		String name = "TestPerson";
		String password = "Password";
		Person person = new Person();

		person.setUsername(name);
		person.setPassword(password);
		personRepository.save(person);
		person = null;
		person = personRepository.findByUsername(name);
		assertNotNull(person);
		assertEquals(name, person.getUsername());
		assertEquals(password, person.getPassword());
	}
	
	
	
	@Test
	public void PersistAndLoadPetPost() {
		
		String username = "TestPerson";
		String password = "Password";
		Person person = new Person();
		person.setUsername(username);
		person.setPassword(password);
		personRepository.save(person);
		
		
		
		PetPost petPost = new PetPost();
		
		
		petPost.setAvailability(true);
		String name = "bob";
		petPost.setName(name);
		String typePet = "cat";
		petPost.setTypeOfPet(typePet);
		String description = "bob is fat";
		petPost.setDescription(description);
		petPost.setOwnedBy(person);
		petPostRepository.save(petPost);
		//post id is autogenerated after save
		int id = petPost.getPetPostId();
		
		petPost = null;
		
		petPost = petPostRepository.findByPetPostId(id);
		assertNotNull(petPost);
		assertEquals(name, petPost.getName());
		assertEquals(typePet, petPost.getTypeOfPet());
		assertEquals(description, petPost.getDescription());
		
		
		
		
	}
	
	
	
	
	
	
	
	
	
}
